language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r dev_requirements.txt
# command to run tests
script:
  - pytest
  - flake8 src tests
  - pylint src tests
